#!/usr/bin/env node
/**
 * Build one normalized roster for the browser drivers.
 *
 * The passport data comes from the SailClear XLSX the extension already
 * generates — that file carries all 13 person fields in normalized form, so it
 * doubles as the roster export and no extension change is needed. Vessel and
 * voyage details, which no passport carries, come from trip.json.
 *
 *   node scripts/agent/roster.mjs <roster.xlsx> [trip.json]
 *
 * Everything a form control constrains is resolved HERE, against the
 * vocabularies shipped inside the government templates. The drivers then pick
 * from a supplied string rather than improvising, which is what stops an agent
 * typing "USA" into a dropdown that only accepts "UNITED STATES".
 */

import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { openWorkbook } from '../lib/xlsx-read.mjs';
import { buildCountryNameMap, buildCountryCodeMap } from '../lib/countries.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');

const xlsxPath = process.argv[2];
const tripPath = process.argv[3] || resolve(HERE, 'trip.json');

if (!xlsxPath) {
  console.error('usage: node scripts/agent/roster.mjs <roster.xlsx> [trip.json]');
  console.error('  roster.xlsx = the SailClear file generated by the extension');
  process.exit(1);
}

const COUNTRY_NVMC = buildCountryNameMap('nvmc');
const COUNTRY_SC = buildCountryNameMap('sailclear');
const COUNTRY_BVI = buildCountryNameMap('bvi');
const COUNTRY_CODE = buildCountryCodeMap();

/** Resolve a country to every vocabulary at once, flagging failures loudly. */
function resolveCountry(raw, label) {
  const v = (raw ?? '').trim();
  if (!v) return { raw: v, nvmc: null, sailclear: null, code: null, ok: false, why: `${label} empty` };
  const nvmc = COUNTRY_NVMC[v] ?? null;
  const sailclear = COUNTRY_SC[v] ?? null;
  const code = COUNTRY_CODE[v] ?? null;
  return {
    raw: v,
    nvmc,
    sailclear,
    code,
    // BVI is a third vocabulary again: UPPERCASE with a parenthesised suffix.
    // Verified live: "VIRGIN ISLANDS (BRITISH)", not NVMC's comma form nor
    // SailClear's title case. The driver still re-checks against the real
    // dropdown before committing.
    bvi: COUNTRY_BVI[v] ?? null,
    ok: Boolean(nvmc && sailclear && code),
    why: nvmc && sailclear && code ? null : `${label} "${v}" not in one or more vocabularies`,
  };
}

/** SailClear writes MM-DD-YYYY; everything downstream wants explicit parts. */
function parseSailclearDate(s) {
  const v = (s ?? '').trim();
  const m = /^(\d{2})-(\d{2})-(\d{4})$/.exec(v);
  if (!m) return null;
  const [, month, day, year] = m;
  return {
    iso: `${year}-${month}-${day}`,
    us: `${month}/${day}/${year}`,
    uk: `${day}/${month}/${year}`,
    day,
    month,
    year,
  };
}

// ------------------------------------------------------------- read inputs

const wb = openWorkbook(resolve(xlsxPath));
const COLS = 'ABCDEFGHIJKLMNOP'.split('');
const grid = {};
for (const c of COLS) grid[c] = wb.readColumn('Individuals', c);

const header = Object.fromEntries(COLS.map((c) => [c, grid[c].get(1) ?? '']));
const maxRow = Math.max(...COLS.flatMap((c) => [...grid[c].keys()]), 1);

const trip = existsSync(tripPath) ? JSON.parse(readFileSync(tripPath, 'utf8')) : null;
if (!trip) {
  console.error(`\n⚠ No trip file at ${tripPath}`);
  console.error('  Copy scripts/agent/trip.example.json to trip.json and fill it in.');
  console.error('  Continuing with people only — the drivers need the voyage data.\n');
}

// ------------------------------------------------------------ build people

const warnings = [];
const people = [];

for (let r = 2; r <= maxRow; r++) {
  const cell = (c) => (grid[c].get(r) ?? '').toString().trim();
  const firstName = cell('A');
  const lastName = cell('B');
  if (!firstName && !lastName) continue;

  const nationality = resolveCountry(cell('E'), `row ${r} nationality`);
  const issueCountry = resolveCountry(cell('J'), `row ${r} country of issue`);
  const birthRaw = cell('G');
  const birthCountry = resolveCountry(birthRaw, `row ${r} birth country`);

  const dob = parseSailclearDate(cell('F'));
  const issued = parseSailclearDate(cell('K'));
  const expires = parseSailclearDate(cell('L'));

  if (!nationality.ok) warnings.push(nationality.why);
  if (!issueCountry.ok) warnings.push(issueCountry.why);
  if (!birthCountry.ok) {
    // Expected: passports usually print a city here, and no vocabulary has it.
    warnings.push(
      `row ${r} birth country "${birthRaw}" looks like a city — BVI does not ask for it, ` +
        `but SailClear requires a country`,
    );
  }
  if (!dob) warnings.push(`row ${r} date of birth unreadable`);
  if (!expires) warnings.push(`row ${r} passport expiry unreadable`);

  people.push({
    row: r,
    firstName,
    lastName,
    middleName: cell('C'),
    sex: cell('D'), // already Male/Female from the generator
    nationality,
    birthCountry,
    documentType: cell('H') || 'Passport',
    documentNumber: cell('I'),
    issueCountry,
    dateOfBirth: dob,
    dateOfIssue: issued,
    dateOfExpiry: expires,
    rank: cell('M') || 'Passenger',
    travelingAs: (cell('M') || 'Passenger').toUpperCase() === 'MASTER' ? 'CREW' : 'PASSENGER',
    countryOfResidence: trip?.defaults?.countryOfResidence
      ? resolveCountry(trip.defaults.countryOfResidence, `row ${r} residence`)
      : null,
  });
}

// --------------------------------------------------------------- voyage

let voyage = null;
if (trip) {
  const regCountry = resolveCountry(
    trip.vessel?.countryOfRegistration,
    'vessel country of registration',
  );
  const embarkCountry = resolveCountry(trip.voyage?.embarkCountry, 'embark country');
  if (!regCountry.ok) warnings.push(regCountry.why);
  if (!embarkCountry.ok) warnings.push(embarkCountry.why);

  voyage = {
    direction: trip.direction ?? 'arrival',
    vessel: { ...trip.vessel, countryOfRegistration: regCountry },
    voyage: { ...trip.voyage, embarkCountry },
    accommodation: trip.accommodation ?? null,
  };

  // NVMC encodes the USVI as a state of the United States, not a country.
  if (embarkCountry.code === 'US' && !trip.voyage?.embarkState) {
    warnings.push(
      'embark state missing — NVMC needs "Virgin Islands" as the state when the embark country is UNITED STATES',
    );
  }
}

// ---------------------------------------------------------------- output

const roster = {
  generatedAt: new Date().toISOString(),
  source: { xlsx: resolve(xlsxPath), trip: trip ? resolve(tripPath) : null },
  header,
  people,
  ...(voyage ?? {}),
  warnings,
};

const outPath = resolve(HERE, 'roster.json');
writeFileSync(outPath, JSON.stringify(roster, null, 2));

console.log(`Roster: ${people.length} people from ${resolve(xlsxPath)}`);
for (const p of people) {
  console.log(
    `  ${String(p.row).padStart(2)}  ${(p.lastName + ', ' + p.firstName).padEnd(26)}` +
      ` ${(p.nationality.nvmc ?? '??').padEnd(22)} ${p.documentNumber.padEnd(12)}` +
      ` DOB ${p.dateOfBirth?.iso ?? '??'}  ${p.travelingAs}`,
  );
}

if (voyage) {
  console.log(
    `\nVoyage: ${voyage.direction} — ${voyage.vessel.name} (${voyage.vessel.registrationNumber})` +
      ` on ${voyage.voyage.intendedDate} ${voyage.voyage.intendedTime ?? ''}`,
  );
  console.log(`  ${voyage.voyage.portOfEmbarkation} -> ${voyage.voyage.portOfEntry}`);
}

if (warnings.length) {
  console.log(`\n⚠ ${warnings.length} thing(s) to check before submitting:`);
  for (const w of [...new Set(warnings)]) console.log(`   - ${w}`);
}

console.log(`\nWrote ${outPath}`);
